default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_URL") { "localhost" } %>
  pool: 5
  reaping_frequency: 30
  timeout: 5000

development:
  <<: *default
  database: currency_exchange_development
  username: docker
  password: docker

production:
  <<: *default
  database: currency_exchange_production

test:
  <<: *default
  database: currency_exchange_test
  username: docker
  password: docker